#! /bin/bash
# Activate the virtual environment, run burstrender.py, and deactivate the virtual environment
# MODIFY THIS LINE TO POINT TO YOUR BURSTRENDER DIRECTORY
. ~/gitlab/burstrender/.venv/bin/activate
# MODIFY THIS LINE TO POINT TO YOUR BURSTRENDER DIRECTORY
python3 ~/gitlab/burstrender/burstrender.py $@
deactivate
