# This YAML file contains configuration settings for the burstrender application.

paths:
  # The path to the directory where the application will store temporary files.
  # Make sure the user running the application has write permissions to this directory
  # and that the directory has enough space to store the temporary files.
  # default = ~/burstrender/working
  working: default

logging:
  # The logging level for the application. Possible values: debug, info, warning, error.
  level: debug
  # The path where log files will be stored. Make sure the user running the application
  # has write permissions to this directory. Log files are limited to 10 MB in size and
  # are rotated when they reach this size. 10 log files are kept before they are deleted.
  path: logs